# Generated by Django 2.2.4 on 2019-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('channelTitle', models.CharField(max_length=50)),
                ('publishedAt', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
